language: cpp
dist: trusty
sudo: required
group: edge

matrix:
  include:

  # gcc build
  - os: linux
    compiler: gcc
    env: 
      - COMPILER=g++-5
      - C_COMPILER=gcc-5

  # clang build
  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-5.0


before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  # make sure CXX is correctly set
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${C_COMPILER}" != "" ]]; then export CC=${COMPILER}; fi
  - cmake --build .
  - cppcheck --force --quiet --error-exitcode=1 .
  - doxygen DoxyFile 2>&1 | tee doxygen.log^

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - cppcheck
      - gcc-5
      - g++-5
      - doxygen
      - graphviz

  
env:
  global:
    - GITHUB_REPO: JimmySnails/IsometricEngine
    - DOXY_DIR: html  
      
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: $GITHUB_REPO
  local_dir: $DOXY_DIR
  on:
    branch: test
